MAKEFILE = Makefile

Draw:
	gcc -Wall ../TERPLUS/bibli.c ../TERPLUS/FirstFit.c TestDraw.c `pkg-config --cflags --libs gtk+-3.0` -o TestDraw
	./TestDraw

Dra:
	gcc -Wall ../TERPLUS/bibli.c ../TERPLUS/algoLourd.c TestDraw.c `pkg-config --cflags --libs gtk+-3.0` -o TestDraw
	./TestDraw